name: Auto Deploy to EC2

on:
  push:
    branches:
      - "main"

permissions:
  id-token: write
  contents: read

env:
  IMAGE_TAG: ${{ github.sha }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ secrets.AWS_OIDC_ROLE }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Gradle
        run: ./gradlew clean build

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Amazon ECR
        run: |
          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | \
          docker login --username AWS \
          --password-stdin ${{ secrets.ECR_URI }}

      - name: Copy application-*.yml
        run: |
          touch ./src/main/resources/application.yml
          echo "${{ secrets.APPLICATION }}" > ./src/main/resources/application.yml
          
      - name: Build and tag Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_TAG }}:${{ env.IMAGE_TAG }} \
          -t ${{ secrets.DOCKER_TAG }}:latest .

      - name: Push Docker image to Amazon ECR
        run: |
          docker push ${{ secrets.DOCKER_TAG }}:${{ env.IMAGE_TAG }}
          docker push ${{ secrets.DOCKER_TAG }}:latest

      - name: Deploy to EC2 with CodeDeploy
        run: |
          aws deploy create-deployment \
          --application-name ${{ secrets.CODE_DEPLOY_APPLICATION_NAME }} \
          --deployment-group-name ${{ secrets.CODE_DEPLOY_GROUP_NAME }} \
          --deployment-config-name CodeDeployDefault.AllAtOnce \
          --description "Deploying Docker image to EC2"